

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Manufacturer : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Manufacturer entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Manufacturer()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Manufacturer(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Manufacturer> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Manufacturer.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Manufacturer_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Manufacturer_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID
        {
            get
            {
                return global::LightSwitchApplication.Manufacturer.DetailsClass.GetValue(this, global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Mfg_Name
        {
            get
            {
                return global::LightSwitchApplication.Manufacturer.DetailsClass.GetValue(this, global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.Mfg_Name);
            }
            set
            {
                global::LightSwitchApplication.Manufacturer.DetailsClass.SetValue(this, global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.Mfg_Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Mfg_Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Mfg_Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Mfg_Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Specialty
        {
            get
            {
                return global::LightSwitchApplication.Manufacturer.DetailsClass.GetValue(this, global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.Specialty);
            }
            set
            {
                global::LightSwitchApplication.Manufacturer.DetailsClass.SetValue(this, global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.Specialty, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Specialty_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Specialty_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Specialty_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.SupplierManufacture> SupplierManufactures
        {
            get
            {
                return global::LightSwitchApplication.Manufacturer.DetailsClass.GetValue(this, global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.SupplierManufactures);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.SupplierManufacture> SupplierManufacturesQuery
        {
            get
            {
                return global::LightSwitchApplication.Manufacturer.DetailsClass.GetQuery(this, global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.SupplierManufactures);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Manufacturer,
                global::LightSwitchApplication.Manufacturer.DetailsClass,
                global::LightSwitchApplication.Manufacturer.DetailsClass.IImplementation,
                global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass>.Entry
                __ManufacturerEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass>.Entry(
                    global::LightSwitchApplication.Manufacturer.DetailsClass.__Manufacturer_CreateNew,
                    global::LightSwitchApplication.Manufacturer.DetailsClass.__Manufacturer_Created,
                    global::LightSwitchApplication.Manufacturer.DetailsClass.__Manufacturer_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Manufacturer __Manufacturer_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Manufacturer> es)
            {
                return new global::LightSwitchApplication.Manufacturer(es);
            }
            private static void __Manufacturer_Created(global::LightSwitchApplication.Manufacturer e)
            {
                e.Manufacturer_Created();
            }
            private static bool __Manufacturer_AllowSaveWithErrors(global::LightSwitchApplication.Manufacturer e)
            {
                bool result = false;
                e.Manufacturer_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, int> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string> Mfg_Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.Mfg_Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string> Specialty
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.Specialty) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, global::LightSwitchApplication.SupplierManufacture> SupplierManufactures
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.SupplierManufactures) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, global::LightSwitchApplication.SupplierManufacture>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID { get; }
                new string Mfg_Name { get; set; }
                new string Specialty { get; set; }
                new global::System.Collections.IEnumerable SupplierManufactures { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, int>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, int>.Entry(
                        "ID",
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Manufacturer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, int>.Data> c, global::LightSwitchApplication.Manufacturer.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.Manufacturer e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.Manufacturer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static int _ID_GetImplementationValue(global::LightSwitchApplication.Manufacturer.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.Manufacturer e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string>.Entry
                    Mfg_Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string>.Entry(
                        "Mfg_Name",
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Mfg_Name_Stub,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Mfg_Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Mfg_Name_Validate,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Mfg_Name_GetImplementationValue,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Mfg_Name_SetImplementationValue,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Mfg_Name_OnValueChanged);
                private static void _Mfg_Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Manufacturer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string>.Data> c, global::LightSwitchApplication.Manufacturer.DetailsClass d, object sf)
                {
                    c(d, ref d._Mfg_Name, sf);
                }
                private static bool _Mfg_Name_ComputeIsReadOnly(global::LightSwitchApplication.Manufacturer e)
                {
                    bool result = false;
                    e.Mfg_Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Mfg_Name_Validate(global::LightSwitchApplication.Manufacturer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Mfg_Name_Validate(r);
                }
                private static string _Mfg_Name_GetImplementationValue(global::LightSwitchApplication.Manufacturer.DetailsClass d)
                {
                    return d.ImplementationEntity.Mfg_Name;
                }
                private static void _Mfg_Name_SetImplementationValue(global::LightSwitchApplication.Manufacturer.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Mfg_Name = v;
                }
                private static void _Mfg_Name_OnValueChanged(global::LightSwitchApplication.Manufacturer e)
                {
                    e.Mfg_Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string>.Entry
                    Specialty = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string>.Entry(
                        "Specialty",
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Specialty_Stub,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Specialty_ComputeIsReadOnly,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Specialty_Validate,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Specialty_GetImplementationValue,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Specialty_SetImplementationValue,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._Specialty_OnValueChanged);
                private static void _Specialty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Manufacturer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string>.Data> c, global::LightSwitchApplication.Manufacturer.DetailsClass d, object sf)
                {
                    c(d, ref d._Specialty, sf);
                }
                private static bool _Specialty_ComputeIsReadOnly(global::LightSwitchApplication.Manufacturer e)
                {
                    bool result = false;
                    e.Specialty_IsReadOnly(ref result);
                    return result;
                }
                private static void _Specialty_Validate(global::LightSwitchApplication.Manufacturer e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Specialty_Validate(r);
                }
                private static string _Specialty_GetImplementationValue(global::LightSwitchApplication.Manufacturer.DetailsClass d)
                {
                    return d.ImplementationEntity.Specialty;
                }
                private static void _Specialty_SetImplementationValue(global::LightSwitchApplication.Manufacturer.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Specialty = v;
                }
                private static void _Specialty_OnValueChanged(global::LightSwitchApplication.Manufacturer e)
                {
                    e.Specialty_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, global::LightSwitchApplication.SupplierManufacture>.Entry
                    SupplierManufactures = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, global::LightSwitchApplication.SupplierManufacture>.Entry(
                        "SupplierManufactures",
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._SupplierManufactures_Stub,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._SupplierManufactures_GetReferencedEntities,
                        global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties._SupplierManufactures_GetEntityCollection);
                private static void _SupplierManufactures_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Manufacturer.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, global::LightSwitchApplication.SupplierManufacture>.Data> c, global::LightSwitchApplication.Manufacturer.DetailsClass d, object sf)
                {
                    c(d, ref d._SupplierManufactures, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.SupplierManufacture> _SupplierManufactures_GetReferencedEntities(global::LightSwitchApplication.Manufacturer.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.SupplierManufacture, global::LightSwitchApplication.SupplierManufacture.DetailsClass>(global::LightSwitchApplication.Manufacturer.DetailsClass.PropertySetProperties.SupplierManufactures, ref d._SupplierManufactures);
                }
                private static global::System.Collections.IEnumerable _SupplierManufactures_GetEntityCollection(global::LightSwitchApplication.Manufacturer.DetailsClass d)
                {
                    return d.ImplementationEntity.SupplierManufactures;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, int>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string>.Data _Mfg_Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, string>.Data _Specialty;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Manufacturer, global::LightSwitchApplication.Manufacturer.DetailsClass, global::LightSwitchApplication.SupplierManufacture>.Data _SupplierManufactures;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Material_Status : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Material_Status entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Material_Status()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Material_Status(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Material_Status> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Material_Status.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Material_Status_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Material_Status_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID
        {
            get
            {
                return global::LightSwitchApplication.Material_Status.DetailsClass.GetValue(this, global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MaterialStatus
        {
            get
            {
                return global::LightSwitchApplication.Material_Status.DetailsClass.GetValue(this, global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties.MaterialStatus);
            }
            set
            {
                global::LightSwitchApplication.Material_Status.DetailsClass.SetValue(this, global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties.MaterialStatus, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MaterialStatus_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MaterialStatus_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MaterialStatus_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Expediting> Expeditings
        {
            get
            {
                return global::LightSwitchApplication.Material_Status.DetailsClass.GetValue(this, global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties.Expeditings);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Expediting> ExpeditingsQuery
        {
            get
            {
                return global::LightSwitchApplication.Material_Status.DetailsClass.GetQuery(this, global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties.Expeditings);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Material_Status,
                global::LightSwitchApplication.Material_Status.DetailsClass,
                global::LightSwitchApplication.Material_Status.DetailsClass.IImplementation,
                global::LightSwitchApplication.Material_Status.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass>.Entry
                __Material_StatusEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass>.Entry(
                    global::LightSwitchApplication.Material_Status.DetailsClass.__Material_Status_CreateNew,
                    global::LightSwitchApplication.Material_Status.DetailsClass.__Material_Status_Created,
                    global::LightSwitchApplication.Material_Status.DetailsClass.__Material_Status_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Material_Status __Material_Status_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Material_Status> es)
            {
                return new global::LightSwitchApplication.Material_Status(es);
            }
            private static void __Material_Status_Created(global::LightSwitchApplication.Material_Status e)
            {
                e.Material_Status_Created();
            }
            private static bool __Material_Status_AllowSaveWithErrors(global::LightSwitchApplication.Material_Status e)
            {
                bool result = false;
                e.Material_Status_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Material_Status.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, int> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, string> MaterialStatus
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties.MaterialStatus) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, global::LightSwitchApplication.Expediting> Expeditings
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties.Expeditings) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, global::LightSwitchApplication.Expediting>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID { get; }
                new string MaterialStatus { get; set; }
                new global::System.Collections.IEnumerable Expeditings { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, int>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, int>.Entry(
                        "ID",
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Material_Status.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, int>.Data> c, global::LightSwitchApplication.Material_Status.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.Material_Status e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.Material_Status e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static int _ID_GetImplementationValue(global::LightSwitchApplication.Material_Status.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.Material_Status e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, string>.Entry
                    MaterialStatus = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, string>.Entry(
                        "MaterialStatus",
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._MaterialStatus_Stub,
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._MaterialStatus_ComputeIsReadOnly,
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._MaterialStatus_Validate,
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._MaterialStatus_GetImplementationValue,
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._MaterialStatus_SetImplementationValue,
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._MaterialStatus_OnValueChanged);
                private static void _MaterialStatus_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Material_Status.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, string>.Data> c, global::LightSwitchApplication.Material_Status.DetailsClass d, object sf)
                {
                    c(d, ref d._MaterialStatus, sf);
                }
                private static bool _MaterialStatus_ComputeIsReadOnly(global::LightSwitchApplication.Material_Status e)
                {
                    bool result = false;
                    e.MaterialStatus_IsReadOnly(ref result);
                    return result;
                }
                private static void _MaterialStatus_Validate(global::LightSwitchApplication.Material_Status e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MaterialStatus_Validate(r);
                }
                private static string _MaterialStatus_GetImplementationValue(global::LightSwitchApplication.Material_Status.DetailsClass d)
                {
                    return d.ImplementationEntity.MaterialStatus;
                }
                private static void _MaterialStatus_SetImplementationValue(global::LightSwitchApplication.Material_Status.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MaterialStatus = v;
                }
                private static void _MaterialStatus_OnValueChanged(global::LightSwitchApplication.Material_Status e)
                {
                    e.MaterialStatus_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, global::LightSwitchApplication.Expediting>.Entry
                    Expeditings = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, global::LightSwitchApplication.Expediting>.Entry(
                        "Expeditings",
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._Expeditings_Stub,
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._Expeditings_GetReferencedEntities,
                        global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties._Expeditings_GetEntityCollection);
                private static void _Expeditings_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Material_Status.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, global::LightSwitchApplication.Expediting>.Data> c, global::LightSwitchApplication.Material_Status.DetailsClass d, object sf)
                {
                    c(d, ref d._Expeditings, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Expediting> _Expeditings_GetReferencedEntities(global::LightSwitchApplication.Material_Status.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Expediting, global::LightSwitchApplication.Expediting.DetailsClass>(global::LightSwitchApplication.Material_Status.DetailsClass.PropertySetProperties.Expeditings, ref d._Expeditings);
                }
                private static global::System.Collections.IEnumerable _Expeditings_GetEntityCollection(global::LightSwitchApplication.Material_Status.DetailsClass d)
                {
                    return d.ImplementationEntity.Expeditings;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, int>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, string>.Data _MaterialStatus;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Material_Status, global::LightSwitchApplication.Material_Status.DetailsClass, global::LightSwitchApplication.Expediting>.Data _Expeditings;
            
        }
    
        #endregion
    }
    
    #endregion
}
