

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class UOM : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the UOM entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UOM()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public UOM(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UOM> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.UOM.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UOM_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UOM_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int id
        {
            get
            {
                return global::LightSwitchApplication.UOM.DetailsClass.GetValue(this, global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UOM1
        {
            get
            {
                return global::LightSwitchApplication.UOM.DetailsClass.GetValue(this, global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.UOM1);
            }
            set
            {
                global::LightSwitchApplication.UOM.DetailsClass.SetValue(this, global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.UOM1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UOM1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UOM1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UOM1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.RFQ_Line> RFQ_Lines
        {
            get
            {
                return global::LightSwitchApplication.UOM.DetailsClass.GetValue(this, global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.RFQ_Lines);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.RFQ_Line> RFQ_LinesQuery
        {
            get
            {
                return global::LightSwitchApplication.UOM.DetailsClass.GetQuery(this, global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.RFQ_Lines);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ChangeOrder> ChangeOrders
        {
            get
            {
                return global::LightSwitchApplication.UOM.DetailsClass.GetValue(this, global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.ChangeOrders);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ChangeOrder> ChangeOrdersQuery
        {
            get
            {
                return global::LightSwitchApplication.UOM.DetailsClass.GetQuery(this, global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.ChangeOrders);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.LineChangeOrder> LineChangeOrders
        {
            get
            {
                return global::LightSwitchApplication.UOM.DetailsClass.GetValue(this, global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.LineChangeOrders);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.LineChangeOrder> LineChangeOrdersQuery
        {
            get
            {
                return global::LightSwitchApplication.UOM.DetailsClass.GetQuery(this, global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.LineChangeOrders);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.UOM,
                global::LightSwitchApplication.UOM.DetailsClass,
                global::LightSwitchApplication.UOM.DetailsClass.IImplementation,
                global::LightSwitchApplication.UOM.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass>.Entry
                __UOMEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass>.Entry(
                    global::LightSwitchApplication.UOM.DetailsClass.__UOM_CreateNew,
                    global::LightSwitchApplication.UOM.DetailsClass.__UOM_Created,
                    global::LightSwitchApplication.UOM.DetailsClass.__UOM_AllowSaveWithErrors);
            private static global::LightSwitchApplication.UOM __UOM_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UOM> es)
            {
                return new global::LightSwitchApplication.UOM(es);
            }
            private static void __UOM_Created(global::LightSwitchApplication.UOM e)
            {
                e.UOM_Created();
            }
            private static bool __UOM_AllowSaveWithErrors(global::LightSwitchApplication.UOM e)
            {
                bool result = false;
                e.UOM_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.UOM.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, int> id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, string> UOM1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.UOM1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.RFQ_Line> RFQ_Lines
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.RFQ_Lines) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.RFQ_Line>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.ChangeOrder> ChangeOrders
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.ChangeOrders) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.ChangeOrder>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.LineChangeOrder> LineChangeOrders
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.LineChangeOrders) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.LineChangeOrder>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int id { get; }
                new string UOM1 { get; set; }
                new global::System.Collections.IEnumerable RFQ_Lines { get; }
                new global::System.Collections.IEnumerable ChangeOrders { get; }
                new global::System.Collections.IEnumerable LineChangeOrders { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, int>.Entry
                    id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, int>.Entry(
                        "id",
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._id_Stub,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._id_ComputeIsReadOnly,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._id_Validate,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._id_OnValueChanged);
                private static void _id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UOM.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, int>.Data> c, global::LightSwitchApplication.UOM.DetailsClass d, object sf)
                {
                    c(d, ref d._id, sf);
                }
                private static bool _id_ComputeIsReadOnly(global::LightSwitchApplication.UOM e)
                {
                    bool result = false;
                    e.id_IsReadOnly(ref result);
                    return result;
                }
                private static void _id_Validate(global::LightSwitchApplication.UOM e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.id_Validate(r);
                }
                private static int _id_GetImplementationValue(global::LightSwitchApplication.UOM.DetailsClass d)
                {
                    return d.ImplementationEntity.id;
                }
                private static void _id_OnValueChanged(global::LightSwitchApplication.UOM e)
                {
                    e.id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, string>.Entry
                    UOM1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, string>.Entry(
                        "UOM1",
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._UOM1_Stub,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._UOM1_ComputeIsReadOnly,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._UOM1_Validate,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._UOM1_GetImplementationValue,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._UOM1_SetImplementationValue,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._UOM1_OnValueChanged);
                private static void _UOM1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UOM.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, string>.Data> c, global::LightSwitchApplication.UOM.DetailsClass d, object sf)
                {
                    c(d, ref d._UOM1, sf);
                }
                private static bool _UOM1_ComputeIsReadOnly(global::LightSwitchApplication.UOM e)
                {
                    bool result = false;
                    e.UOM1_IsReadOnly(ref result);
                    return result;
                }
                private static void _UOM1_Validate(global::LightSwitchApplication.UOM e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UOM1_Validate(r);
                }
                private static string _UOM1_GetImplementationValue(global::LightSwitchApplication.UOM.DetailsClass d)
                {
                    return d.ImplementationEntity.UOM1;
                }
                private static void _UOM1_SetImplementationValue(global::LightSwitchApplication.UOM.DetailsClass d, string v)
                {
                    d.ImplementationEntity.UOM1 = v;
                }
                private static void _UOM1_OnValueChanged(global::LightSwitchApplication.UOM e)
                {
                    e.UOM1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.RFQ_Line>.Entry
                    RFQ_Lines = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.RFQ_Line>.Entry(
                        "RFQ_Lines",
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._RFQ_Lines_Stub,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._RFQ_Lines_GetReferencedEntities,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._RFQ_Lines_GetEntityCollection);
                private static void _RFQ_Lines_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UOM.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.RFQ_Line>.Data> c, global::LightSwitchApplication.UOM.DetailsClass d, object sf)
                {
                    c(d, ref d._RFQ_Lines, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.RFQ_Line> _RFQ_Lines_GetReferencedEntities(global::LightSwitchApplication.UOM.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.RFQ_Line, global::LightSwitchApplication.RFQ_Line.DetailsClass>(global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.RFQ_Lines, ref d._RFQ_Lines);
                }
                private static global::System.Collections.IEnumerable _RFQ_Lines_GetEntityCollection(global::LightSwitchApplication.UOM.DetailsClass d)
                {
                    return d.ImplementationEntity.RFQ_Lines;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.ChangeOrder>.Entry
                    ChangeOrders = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.ChangeOrder>.Entry(
                        "ChangeOrders",
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._ChangeOrders_Stub,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._ChangeOrders_GetReferencedEntities,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._ChangeOrders_GetEntityCollection);
                private static void _ChangeOrders_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UOM.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.ChangeOrder>.Data> c, global::LightSwitchApplication.UOM.DetailsClass d, object sf)
                {
                    c(d, ref d._ChangeOrders, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ChangeOrder> _ChangeOrders_GetReferencedEntities(global::LightSwitchApplication.UOM.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ChangeOrder, global::LightSwitchApplication.ChangeOrder.DetailsClass>(global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.ChangeOrders, ref d._ChangeOrders);
                }
                private static global::System.Collections.IEnumerable _ChangeOrders_GetEntityCollection(global::LightSwitchApplication.UOM.DetailsClass d)
                {
                    return d.ImplementationEntity.ChangeOrders;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.LineChangeOrder>.Entry
                    LineChangeOrders = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.LineChangeOrder>.Entry(
                        "LineChangeOrders",
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._LineChangeOrders_Stub,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._LineChangeOrders_GetReferencedEntities,
                        global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties._LineChangeOrders_GetEntityCollection);
                private static void _LineChangeOrders_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.UOM.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.LineChangeOrder>.Data> c, global::LightSwitchApplication.UOM.DetailsClass d, object sf)
                {
                    c(d, ref d._LineChangeOrders, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.LineChangeOrder> _LineChangeOrders_GetReferencedEntities(global::LightSwitchApplication.UOM.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.LineChangeOrder, global::LightSwitchApplication.LineChangeOrder.DetailsClass>(global::LightSwitchApplication.UOM.DetailsClass.PropertySetProperties.LineChangeOrders, ref d._LineChangeOrders);
                }
                private static global::System.Collections.IEnumerable _LineChangeOrders_GetEntityCollection(global::LightSwitchApplication.UOM.DetailsClass d)
                {
                    return d.ImplementationEntity.LineChangeOrders;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, int>.Data _id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, string>.Data _UOM1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.RFQ_Line>.Data _RFQ_Lines;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.ChangeOrder>.Data _ChangeOrders;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.UOM, global::LightSwitchApplication.UOM.DetailsClass, global::LightSwitchApplication.LineChangeOrder>.Data _LineChangeOrders;
            
        }
    
        #endregion
    }
    
    #endregion
}
