

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Preference : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Preference entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Preference()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Preference(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Preference> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Preference.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Preference_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Preference_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID
        {
            get
            {
                return global::LightSwitchApplication.Preference.DetailsClass.GetValue(this, global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PreferenceType
        {
            get
            {
                return global::LightSwitchApplication.Preference.DetailsClass.GetValue(this, global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties.PreferenceType);
            }
            set
            {
                global::LightSwitchApplication.Preference.DetailsClass.SetValue(this, global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties.PreferenceType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PreferenceType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PreferenceType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PreferenceType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Client_Approved> Client_Approveds
        {
            get
            {
                return global::LightSwitchApplication.Preference.DetailsClass.GetValue(this, global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties.Client_Approveds);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Client_Approved> Client_ApprovedsQuery
        {
            get
            {
                return global::LightSwitchApplication.Preference.DetailsClass.GetQuery(this, global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties.Client_Approveds);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Preference,
                global::LightSwitchApplication.Preference.DetailsClass,
                global::LightSwitchApplication.Preference.DetailsClass.IImplementation,
                global::LightSwitchApplication.Preference.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass>.Entry
                __PreferenceEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass>.Entry(
                    global::LightSwitchApplication.Preference.DetailsClass.__Preference_CreateNew,
                    global::LightSwitchApplication.Preference.DetailsClass.__Preference_Created,
                    global::LightSwitchApplication.Preference.DetailsClass.__Preference_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Preference __Preference_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Preference> es)
            {
                return new global::LightSwitchApplication.Preference(es);
            }
            private static void __Preference_Created(global::LightSwitchApplication.Preference e)
            {
                e.Preference_Created();
            }
            private static bool __Preference_AllowSaveWithErrors(global::LightSwitchApplication.Preference e)
            {
                bool result = false;
                e.Preference_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Preference.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, int> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, string> PreferenceType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties.PreferenceType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, global::LightSwitchApplication.Client_Approved> Client_Approveds
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties.Client_Approveds) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, global::LightSwitchApplication.Client_Approved>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID { get; }
                new string PreferenceType { get; set; }
                new global::System.Collections.IEnumerable Client_Approveds { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, int>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, int>.Entry(
                        "ID",
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Preference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, int>.Data> c, global::LightSwitchApplication.Preference.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.Preference e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.Preference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static int _ID_GetImplementationValue(global::LightSwitchApplication.Preference.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.Preference e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, string>.Entry
                    PreferenceType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, string>.Entry(
                        "PreferenceType",
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._PreferenceType_Stub,
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._PreferenceType_ComputeIsReadOnly,
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._PreferenceType_Validate,
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._PreferenceType_GetImplementationValue,
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._PreferenceType_SetImplementationValue,
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._PreferenceType_OnValueChanged);
                private static void _PreferenceType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Preference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, string>.Data> c, global::LightSwitchApplication.Preference.DetailsClass d, object sf)
                {
                    c(d, ref d._PreferenceType, sf);
                }
                private static bool _PreferenceType_ComputeIsReadOnly(global::LightSwitchApplication.Preference e)
                {
                    bool result = false;
                    e.PreferenceType_IsReadOnly(ref result);
                    return result;
                }
                private static void _PreferenceType_Validate(global::LightSwitchApplication.Preference e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PreferenceType_Validate(r);
                }
                private static string _PreferenceType_GetImplementationValue(global::LightSwitchApplication.Preference.DetailsClass d)
                {
                    return d.ImplementationEntity.PreferenceType;
                }
                private static void _PreferenceType_SetImplementationValue(global::LightSwitchApplication.Preference.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PreferenceType = v;
                }
                private static void _PreferenceType_OnValueChanged(global::LightSwitchApplication.Preference e)
                {
                    e.PreferenceType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, global::LightSwitchApplication.Client_Approved>.Entry
                    Client_Approveds = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, global::LightSwitchApplication.Client_Approved>.Entry(
                        "Client_Approveds",
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._Client_Approveds_Stub,
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._Client_Approveds_GetReferencedEntities,
                        global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties._Client_Approveds_GetEntityCollection);
                private static void _Client_Approveds_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Preference.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, global::LightSwitchApplication.Client_Approved>.Data> c, global::LightSwitchApplication.Preference.DetailsClass d, object sf)
                {
                    c(d, ref d._Client_Approveds, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Client_Approved> _Client_Approveds_GetReferencedEntities(global::LightSwitchApplication.Preference.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Client_Approved, global::LightSwitchApplication.Client_Approved.DetailsClass>(global::LightSwitchApplication.Preference.DetailsClass.PropertySetProperties.Client_Approveds, ref d._Client_Approveds);
                }
                private static global::System.Collections.IEnumerable _Client_Approveds_GetEntityCollection(global::LightSwitchApplication.Preference.DetailsClass d)
                {
                    return d.ImplementationEntity.Client_Approveds;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, int>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, string>.Data _PreferenceType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Preference, global::LightSwitchApplication.Preference.DetailsClass, global::LightSwitchApplication.Client_Approved>.Data _Client_Approveds;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Project : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Project entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Project()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Project(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Project> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Project.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Project_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Project_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID
        {
            get
            {
                return global::LightSwitchApplication.Project.DetailsClass.GetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ProjectNo
        {
            get
            {
                return global::LightSwitchApplication.Project.DetailsClass.GetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ProjectNo);
            }
            set
            {
                global::LightSwitchApplication.Project.DetailsClass.SetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ProjectNo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectNo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectNo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectNo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Project.DetailsClass.GetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Project.DetailsClass.SetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Project_Stakeholder> Project_Stakeholders
        {
            get
            {
                return global::LightSwitchApplication.Project.DetailsClass.GetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Project_Stakeholders);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Project_Stakeholder> Project_StakeholdersQuery
        {
            get
            {
                return global::LightSwitchApplication.Project.DetailsClass.GetQuery(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Project_Stakeholders);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.RFQ_PItem> RFQ_P
        {
            get
            {
                return global::LightSwitchApplication.Project.DetailsClass.GetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.RFQ_P);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.RFQ_PItem> RFQ_PQuery
        {
            get
            {
                return global::LightSwitchApplication.Project.DetailsClass.GetQuery(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.RFQ_P);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Client Client1
        {
            get
            {
                return global::LightSwitchApplication.Project.DetailsClass.GetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Client1);
            }
            set
            {
                global::LightSwitchApplication.Project.DetailsClass.SetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Client1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Phase Phase1
        {
            get
            {
                return global::LightSwitchApplication.Project.DetailsClass.GetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Phase1);
            }
            set
            {
                global::LightSwitchApplication.Project.DetailsClass.SetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Phase1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phase1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phase1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phase1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Year Year1
        {
            get
            {
                return global::LightSwitchApplication.Project.DetailsClass.GetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Year1);
            }
            set
            {
                global::LightSwitchApplication.Project.DetailsClass.SetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Year1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Year1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Year1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Year1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ProjectClassification ProjectClassification
        {
            get
            {
                return global::LightSwitchApplication.Project.DetailsClass.GetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ProjectClassification);
            }
            set
            {
                global::LightSwitchApplication.Project.DetailsClass.SetValue(this, global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ProjectClassification, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectClassification_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectClassification_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectClassification_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Project,
                global::LightSwitchApplication.Project.DetailsClass,
                global::LightSwitchApplication.Project.DetailsClass.IImplementation,
                global::LightSwitchApplication.Project.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass>.Entry
                __ProjectEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass>.Entry(
                    global::LightSwitchApplication.Project.DetailsClass.__Project_CreateNew,
                    global::LightSwitchApplication.Project.DetailsClass.__Project_Created,
                    global::LightSwitchApplication.Project.DetailsClass.__Project_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Project __Project_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Project> es)
            {
                return new global::LightSwitchApplication.Project(es);
            }
            private static void __Project_Created(global::LightSwitchApplication.Project e)
            {
                e.Project_Created();
            }
            private static bool __Project_AllowSaveWithErrors(global::LightSwitchApplication.Project e)
            {
                bool result = false;
                e.Project_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Project.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, int> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string> ProjectNo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ProjectNo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Project_Stakeholder> Project_Stakeholders
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Project_Stakeholders) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Project_Stakeholder>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.RFQ_PItem> RFQ_P
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.RFQ_P) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.RFQ_PItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Client> Client1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Client1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Client>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Phase> Phase1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Phase1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Phase>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Year> Year1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Year1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Year>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.ProjectClassification> ProjectClassification
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ProjectClassification) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.ProjectClassification>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID { get; }
                new string ProjectNo { get; set; }
                new string Name { get; set; }
                new global::System.Collections.IEnumerable Project_Stakeholders { get; }
                new global::System.Collections.IEnumerable RFQ_P { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Client1 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Phase1 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Year1 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ProjectClassification { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, int>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, int>.Entry(
                        "ID",
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Project.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, int>.Data> c, global::LightSwitchApplication.Project.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.Project e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.Project e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static int _ID_GetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.Project e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string>.Entry
                    ProjectNo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string>.Entry(
                        "ProjectNo",
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectNo_Stub,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectNo_ComputeIsReadOnly,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectNo_Validate,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectNo_GetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectNo_SetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectNo_OnValueChanged);
                private static void _ProjectNo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Project.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string>.Data> c, global::LightSwitchApplication.Project.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectNo, sf);
                }
                private static bool _ProjectNo_ComputeIsReadOnly(global::LightSwitchApplication.Project e)
                {
                    bool result = false;
                    e.ProjectNo_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectNo_Validate(global::LightSwitchApplication.Project e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectNo_Validate(r);
                }
                private static string _ProjectNo_GetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectNo;
                }
                private static void _ProjectNo_SetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ProjectNo = v;
                }
                private static void _ProjectNo_OnValueChanged(global::LightSwitchApplication.Project e)
                {
                    e.ProjectNo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Project.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string>.Data> c, global::LightSwitchApplication.Project.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Project e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Project e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Project e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Project_Stakeholder>.Entry
                    Project_Stakeholders = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Project_Stakeholder>.Entry(
                        "Project_Stakeholders",
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Project_Stakeholders_Stub,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Project_Stakeholders_GetReferencedEntities,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Project_Stakeholders_GetEntityCollection);
                private static void _Project_Stakeholders_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Project.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Project_Stakeholder>.Data> c, global::LightSwitchApplication.Project.DetailsClass d, object sf)
                {
                    c(d, ref d._Project_Stakeholders, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Project_Stakeholder> _Project_Stakeholders_GetReferencedEntities(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Project_Stakeholder, global::LightSwitchApplication.Project_Stakeholder.DetailsClass>(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Project_Stakeholders, ref d._Project_Stakeholders);
                }
                private static global::System.Collections.IEnumerable _Project_Stakeholders_GetEntityCollection(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.ImplementationEntity.Project_Stakeholders;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.RFQ_PItem>.Entry
                    RFQ_P = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.RFQ_PItem>.Entry(
                        "RFQ_P",
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._RFQ_P_Stub,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._RFQ_P_GetReferencedEntities,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._RFQ_P_GetEntityCollection);
                private static void _RFQ_P_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Project.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.RFQ_PItem>.Data> c, global::LightSwitchApplication.Project.DetailsClass d, object sf)
                {
                    c(d, ref d._RFQ_P, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.RFQ_PItem> _RFQ_P_GetReferencedEntities(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.RFQ_PItem, global::LightSwitchApplication.RFQ_PItem.DetailsClass>(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.RFQ_P, ref d._RFQ_P);
                }
                private static global::System.Collections.IEnumerable _RFQ_P_GetEntityCollection(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.ImplementationEntity.RFQ_P;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Client>.Entry
                    Client1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Client>.Entry(
                        "Client1",
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Client1_Stub,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Client1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Client1_Validate,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Client1_GetCoreImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Client1_GetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Client1_SetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Client1_Refresh,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Client1_OnValueChanged);
                private static void _Client1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Project.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Client>.Data> c, global::LightSwitchApplication.Project.DetailsClass d, object sf)
                {
                    c(d, ref d._Client1, sf);
                }
                private static bool _Client1_ComputeIsReadOnly(global::LightSwitchApplication.Project e)
                {
                    bool result = false;
                    e.Client1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Client1_Validate(global::LightSwitchApplication.Project e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Client1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Client1_GetCoreImplementationValue(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.ImplementationEntity.Client1;
                }
                private static global::LightSwitchApplication.Client _Client1_GetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Client1, ref d._Client1);
                }
                private static void _Client1_SetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d, global::LightSwitchApplication.Client v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Client1, ref d._Client1, (i, ev) => i.Client1 = ev, v);
                }
                private static void _Client1_Refresh(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Client1, ref d._Client1);
                }
                private static void _Client1_OnValueChanged(global::LightSwitchApplication.Project e)
                {
                    e.Client1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Phase>.Entry
                    Phase1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Phase>.Entry(
                        "Phase1",
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Phase1_Stub,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Phase1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Phase1_Validate,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Phase1_GetCoreImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Phase1_GetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Phase1_SetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Phase1_Refresh,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Phase1_OnValueChanged);
                private static void _Phase1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Project.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Phase>.Data> c, global::LightSwitchApplication.Project.DetailsClass d, object sf)
                {
                    c(d, ref d._Phase1, sf);
                }
                private static bool _Phase1_ComputeIsReadOnly(global::LightSwitchApplication.Project e)
                {
                    bool result = false;
                    e.Phase1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Phase1_Validate(global::LightSwitchApplication.Project e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Phase1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Phase1_GetCoreImplementationValue(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.ImplementationEntity.Phase1;
                }
                private static global::LightSwitchApplication.Phase _Phase1_GetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Phase, global::LightSwitchApplication.Phase.DetailsClass>(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Phase1, ref d._Phase1);
                }
                private static void _Phase1_SetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d, global::LightSwitchApplication.Phase v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Phase1, ref d._Phase1, (i, ev) => i.Phase1 = ev, v);
                }
                private static void _Phase1_Refresh(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Phase1, ref d._Phase1);
                }
                private static void _Phase1_OnValueChanged(global::LightSwitchApplication.Project e)
                {
                    e.Phase1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Year>.Entry
                    Year1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Year>.Entry(
                        "Year1",
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Year1_Stub,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Year1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Year1_Validate,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Year1_GetCoreImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Year1_GetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Year1_SetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Year1_Refresh,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._Year1_OnValueChanged);
                private static void _Year1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Project.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Year>.Data> c, global::LightSwitchApplication.Project.DetailsClass d, object sf)
                {
                    c(d, ref d._Year1, sf);
                }
                private static bool _Year1_ComputeIsReadOnly(global::LightSwitchApplication.Project e)
                {
                    bool result = false;
                    e.Year1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Year1_Validate(global::LightSwitchApplication.Project e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Year1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Year1_GetCoreImplementationValue(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.ImplementationEntity.Year1;
                }
                private static global::LightSwitchApplication.Year _Year1_GetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Year, global::LightSwitchApplication.Year.DetailsClass>(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Year1, ref d._Year1);
                }
                private static void _Year1_SetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d, global::LightSwitchApplication.Year v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Year1, ref d._Year1, (i, ev) => i.Year1 = ev, v);
                }
                private static void _Year1_Refresh(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.Year1, ref d._Year1);
                }
                private static void _Year1_OnValueChanged(global::LightSwitchApplication.Project e)
                {
                    e.Year1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.ProjectClassification>.Entry
                    ProjectClassification = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.ProjectClassification>.Entry(
                        "ProjectClassification",
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectClassification_Stub,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectClassification_ComputeIsReadOnly,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectClassification_Validate,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectClassification_GetCoreImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectClassification_GetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectClassification_SetImplementationValue,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectClassification_Refresh,
                        global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties._ProjectClassification_OnValueChanged);
                private static void _ProjectClassification_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Project.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.ProjectClassification>.Data> c, global::LightSwitchApplication.Project.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectClassification, sf);
                }
                private static bool _ProjectClassification_ComputeIsReadOnly(global::LightSwitchApplication.Project e)
                {
                    bool result = false;
                    e.ProjectClassification_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProjectClassification_Validate(global::LightSwitchApplication.Project e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProjectClassification_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ProjectClassification_GetCoreImplementationValue(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectClassification;
                }
                private static global::LightSwitchApplication.ProjectClassification _ProjectClassification_GetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ProjectClassification, global::LightSwitchApplication.ProjectClassification.DetailsClass>(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ProjectClassification, ref d._ProjectClassification);
                }
                private static void _ProjectClassification_SetImplementationValue(global::LightSwitchApplication.Project.DetailsClass d, global::LightSwitchApplication.ProjectClassification v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ProjectClassification, ref d._ProjectClassification, (i, ev) => i.ProjectClassification = ev, v);
                }
                private static void _ProjectClassification_Refresh(global::LightSwitchApplication.Project.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Project.DetailsClass.PropertySetProperties.ProjectClassification, ref d._ProjectClassification);
                }
                private static void _ProjectClassification_OnValueChanged(global::LightSwitchApplication.Project e)
                {
                    e.ProjectClassification_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, int>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string>.Data _ProjectNo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Project_Stakeholder>.Data _Project_Stakeholders;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.RFQ_PItem>.Data _RFQ_P;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Client>.Data _Client1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Phase>.Data _Phase1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.Year>.Data _Year1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass, global::LightSwitchApplication.ProjectClassification>.Data _ProjectClassification;
            
        }
    
        #endregion
    }
    
    #endregion
}
